spring:
  application:
    name: PeerRequest
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${PR_KEYCLOAK_CLIENT_ID}
            client-secret: ${PR_KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${PR_KEYCLOAK_URL}/realms/PeerRequest
            user-name-attribute: preferred_username
  datasource:
    url: ${PR_DATABASE_URL}
    username: ${PR_DATABASE_USER}
    password: ${PR_DATABASE_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher