spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: PeerRequest
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${PR_KEYCLOAK_CLIENT_ID}
            client-secret: ${PR_KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${PR_KEYCLOAK_URL}/realms/${PR_KEYCLOAK_REALM}
            user-name-attribute: preferred_username
  datasource:
    url: ${PR_DATABASE_URL}
    username: ${PR_DATABASE_USER}
    password: ${PR_DATABASE_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  mail:
    host: ${PR_SMTP_SERVER}
    port: ${PR_SMTP_PORT}
    username: ${PR_SMTP_USER_NAME}
    password: ${PR_SMTP_PW}
    protocol: smtp
    tls: true
    from: ${PR_SMTP_EMAIL}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: ${PR_SMTP_SERVER}
  load: ${PR_LOAD_EXAMPLE:FALSE}
server:
  port: ${PORT:8080}
keycloak:
  admin:
    serverUrl: ${PR_KEYCLOAK_URL}
    realm: ${PR_KEYCLOAK_REALM}
    admin-realm: ${PR_KEYCLOAK_ADMIN_REALM:master}
    username: ${PR_KEYCLOAK_ADMIN_USER:admin}
    password: ${PR_KEYCLOAK_ADMIN_PASSWORD}
    clientId: ${PR_KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}

---

spring:
  config:
    activate:
      on-profile: "test"
  application:
    name: PeerRequestTest
  datasource:
    url: jdbc:tc:postgresql:14.1:///integration-tests-db?TC_TMPFS=/var/lib/postgresql/data:rw
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate.ddl-auto: update
    show-sql: ${$SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB